// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7IVoMhpmc2BhwMuW72zvQGRbyt-tAqiE',
    appId: '1:647866702246:web:1fa95f80114e142c9f1767',
    messagingSenderId: '647866702246',
    projectId: 'hooaah-fbea3',
    authDomain: 'hooaah-fbea3.firebaseapp.com',
    storageBucket: 'hooaah-fbea3.firebasestorage.app',
    measurementId: 'G-3W3JDJFK04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQagevbGNIl2pTf3Ltf_lm1K1mUHMXQV8',
    appId: '1:647866702246:android:e12b368fe75582df9f1767',
    messagingSenderId: '647866702246',
    projectId: 'hooaah-fbea3',
    storageBucket: 'hooaah-fbea3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgYjKx5er0Zx9DFBs4mgEqWbPWqVuDebo',
    appId: '1:647866702246:ios:15dff8e26b3e08399f1767',
    messagingSenderId: '647866702246',
    projectId: 'hooaah-fbea3',
    storageBucket: 'hooaah-fbea3.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgYjKx5er0Zx9DFBs4mgEqWbPWqVuDebo',
    appId: '1:647866702246:ios:15dff8e26b3e08399f1767',
    messagingSenderId: '647866702246',
    projectId: 'hooaah-fbea3',
    storageBucket: 'hooaah-fbea3.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7IVoMhpmc2BhwMuW72zvQGRbyt-tAqiE',
    appId: '1:647866702246:web:ca8d048fcdd0ba849f1767',
    messagingSenderId: '647866702246',
    projectId: 'hooaah-fbea3',
    authDomain: 'hooaah-fbea3.firebaseapp.com',
    storageBucket: 'hooaah-fbea3.firebasestorage.app',
    measurementId: 'G-0QHGYC377N',
  );

}